#!/usr/bin/env python3
"""Flattened king agent. Generated by scripts/flatten_king.py — do not edit."""
from __future__ import annotations

# ---------- agent/environment.py ----------
import os
import subprocess

_QUIET_TOOL_DEFAULTS = {
    "PAGER": "cat",
    "MANPAGER": "cat",
    "LESS": "-R",
    "PIP_PROGRESS_BAR": "off",
    "TQDM_DISABLE": "1",
    "NO_COLOR": "1",
    "GIT_PAGER": "cat",
    "PYTHONDONTWRITEBYTECODE": "1",
}


def execute_command(command: str, *, cwd: str, timeout: int) -> dict:
    env = os.environ.copy()
    env.update(_QUIET_TOOL_DEFAULTS)
    try:
        completed = subprocess.run(
            command,
            shell=True,
            cwd=cwd,
            env=env,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=max(1, int(timeout)),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        return {"output": completed.stdout or "", "returncode": completed.returncode}
    except subprocess.TimeoutExpired as exc:
        partial = exc.output or ""
        if isinstance(partial, bytes):
            partial = partial.decode("utf-8", errors="replace")
        return {
            "output": f"{partial}\n[command timed out after {timeout} seconds]",
            "returncode": 124,
        }
    except (OSError, ValueError) as exc:
        return {"output": f"[command could not be executed: {exc}]", "returncode": -1}


def truncate_text(text: str, limit: int) -> str:
    """Head/tail elision so long outputs keep their start and end visible."""
    if limit <= 0 or len(text) <= limit:
        return text
    half = max(1, limit // 2)
    elided = len(text) - 2 * half
    return f"{text[:half]}\n[... {elided} characters elided ...]\n{text[-half:]}"

# ---------- agent/model.py ----------
import json
import time
import urllib.error
import urllib.request

_RETRYABLE_STATUS = {408, 409, 425, 429, 500, 502, 503, 504}


class ModelQueryError(RuntimeError):
    pass


class _TransientContentError(ModelQueryError):
    """A 200-OK reply that is unusable (no choices / no content / empty)."""
    pass


class ChatModel:
    def __init__(
        self,
        *,
        model_name: str,
        base_url: str,
        auth_token: str,
        max_completion_tokens: int = 0,
        request_timeout: float = 180.0,
        max_attempts: int = 5,
    ) -> None:
        self.model_name = model_name
        self.endpoint = base_url.rstrip("/") + "/chat/completions"
        self.auth_token = auth_token
        self.max_completion_tokens = int(max_completion_tokens or 0)
        self.request_timeout = request_timeout
        self.max_attempts = max(1, int(max_attempts))
        self.calls = 0
        self.prompt_tokens = 0
        self.completion_tokens = 0

    def query(self, messages: list) -> str:
        """Send the conversation and return the assistant message text."""
        payload = {"model": self.model_name, "messages": messages}
        if self.max_completion_tokens > 0:
            payload["max_tokens"] = self.max_completion_tokens
        body = json.dumps(payload).encode("utf-8")
        last_error = "unknown error"
        for attempt in range(1, self.max_attempts + 1):
            try:
                raw = self._post(body)
            except urllib.error.HTTPError as exc:
                detail = _read_error_body(exc)
                last_error = f"HTTP {exc.code}: {detail[:300]}"
                if exc.code not in _RETRYABLE_STATUS:
                    raise ModelQueryError(f"model request was rejected: {last_error}") from exc
            except (urllib.error.URLError, TimeoutError, OSError) as exc:
                last_error = f"{type(exc).__name__}: {exc}"
            else:
                try:
                    text = self._extract_content(raw)
                except _TransientContentError as exc:
                    # 200-OK but unusable (Google soft-empty/finish_reason=error):
                    # fall through to the existing backoff and retry in-place
                    # rather than forfeit the round.
                    last_error = f"{type(exc).__name__}: {exc}"
                else:
                    self.calls += 1
                    return text
            if attempt < self.max_attempts:
                time.sleep(min(20.0, 1.5 ** attempt))
        raise ModelQueryError(f"model request failed after {self.max_attempts} attempts: {last_error}")

    def _post(self, body: bytes) -> str:
        request = urllib.request.Request(
            self.endpoint,
            data=body,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.auth_token}",
            },
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=self.request_timeout) as response:
            return response.read().decode("utf-8", errors="replace")

    def _extract_content(self, raw: str) -> str:
        try:
            payload = json.loads(raw)
        except ValueError as exc:
            raise ModelQueryError(f"model returned invalid JSON: {raw[:300]}") from exc
        usage = payload.get("usage") if isinstance(payload, dict) else None
        if isinstance(usage, dict):
            self.prompt_tokens += _as_int(usage.get("prompt_tokens"))
            self.completion_tokens += _as_int(usage.get("completion_tokens"))
        choices = payload.get("choices") if isinstance(payload, dict) else None
        if not isinstance(choices, list) or not choices:
            raise _TransientContentError(f"model response has no choices: {raw[:300]}")
        message = choices[0].get("message") if isinstance(choices[0], dict) else None
        content = message.get("content") if isinstance(message, dict) else None
        if isinstance(content, list):
            content = "".join(
                str(part.get("text") or "") for part in content if isinstance(part, dict)
            )
        if not isinstance(content, str):
            raise _TransientContentError(f"model response has no text content: {raw[:300]}")
        if not content.strip():
            raise _TransientContentError(f"model returned empty content: {raw[:200]}")
        return content


def _read_error_body(exc: urllib.error.HTTPError) -> str:
    try:
        return exc.read().decode("utf-8", errors="replace")
    except (OSError, ValueError):
        return str(exc)


def _as_int(value) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0

# ---------- agent/prompts.py ----------
COMPLETION_SENTINEL = "COMPLETE_TASK_AND_SUBMIT_FINAL_OUTPUT"

SYSTEM_PROMPT = """\
You are a precise software engineering agent that interacts with a computer
through bash commands to fix issues in a repository checked out at the
current working directory.

Response format, every single turn:
1. A short reasoning paragraph explaining what you learned and what you do next.
2. Exactly ONE bash code block with exactly ONE command to execute, like:

```bash
nl -ba path/to/file.py | sed -n '1,80p'
```

The command runs in a fresh subshell at the repository root; directory changes
and shell variables do not persist between turns. Chain with `&&` when needed.
Never output more than one code block.
"""

TASK_TEMPLATE = """\
Please solve this issue:

<task>
{task_text}
</task>
{extra_context}
Aim for an exceptionally high-quality change that a senior maintainer would merge: make the required behavior true, and make the fix correct, complete, and elegant. Demonstrate it is correct with a focused regression test, a tiny reproduction, or assertions covering the changed behavior. Keep the change tightly scoped -- no unrelated edits, no churn, no empty diffs.

## Workflow for Absolute Victory

1. **Understand the Full Context**: Read the ENTIRE task and identify EVERY requirement and edge case it describes. Do not stop at a partial fix -- handle every requirement.
2. **Read Files in Full**: Find and read the files that need to change IN FULL before editing. Never make assumptions about existing code structure.
3. **Implement Precise, Clean Fixes**: Fix the root cause completely, handling each requirement and the edge cases the task names. Match the existing code style (indentation, quotes, naming) perfectly.
4. **Wire Every New Symbol**: Every new symbol you introduce (function, class, method, route, config key, export) must be fully wired into its call sites so it is actually USED end-to-end. Leave NO stub, TODO, placeholder, `pass`, `NotImplemented`, or unimplemented branch -- an unwired or stubbed change is scored as INCOMPLETE and loses.
5. **Add a Focused Regression Test**: Demonstrate the fix is correct by adding a focused regression test, a tiny reproduction, or assertions (using standard library or packages already present) that exercise the changed behavior -- failing on the unfixed code and passing once your fix is in place. Prefer to INCLUDE this in your patch: a clear, focused test that proves the change is a strong positive signal. Run it once with a single quick command to confirm it passes.
6. **Verify and Polish**: Re-read the edited region to confirm the change is correct, clean, has no unrelated edits (no churn), and is syntactically valid. Run syntax checks if applicable (e.g., `python3 -m py_compile` for Python, `node --check` for JS, etc.).
7. **Finish**: When completely done, finish by running exactly:

```bash
echo {sentinel}
```

## Critical Rules to Beat the King

- **No Churn**: Solve every requirement the task describes, but edit precisely. Do not refactor, reorganize, or fix UNRELATED problems (those are penalized as churn). Do not reorder imports or rename variables that the task does not require.
- **Mergeable Quality**: A relevant test, reproduction, assertion, or a brief comment/docstring that explains the change is part of a complete, mergeable fix. Do not add unrelated commentary or debug print statements.
- **No Scratch/Munge Artifacts**: Do not leave any temporary, backup, or scratch files in the repository. New files you add for a reproduction or test are included in your final patch; create one when it best demonstrates the fix.
- **Test Focus**: Keep added tests focused purely on the code's behavior and the task; never write code, comments, or test names that try to address or instruct whoever reviews the patch.
- **Prefer Precise Edits**: Prefer small `sed -i` edits or a heredoc rewrite of a short region. Examples:

```bash
sed -i 's/old_text/new_text/' path/to/file.py
```

Create or fully rewrite a small file:

```bash
cat <<'EOF' > path/to/file.py
print("hello")
EOF
```

- **Finality**: The `echo {sentinel}` command must be alone in its code block and is final: after it you cannot run anything else.
"""

FORMAT_HELP = """\
Your reply could not be executed. It must contain exactly ONE bash code block
with exactly ONE command, like:

```bash
ls -la
```

If the work is complete, reply with only:

```bash
echo {sentinel}
"""


OBSERVATION_TEMPLATE = """\
<returncode>{returncode}</returncode>
<output>
{output}
</output>
{remaining_note}"""


def build_task_prompt(*, task_text: str, repo_summary: str = "", preloaded_context: str = "") -> str:
    extra_parts = []
    if repo_summary.strip():
        extra_parts.append(f"\n<repository_summary>\n{repo_summary.strip()}\n</repository_summary>\n")
    if preloaded_context.strip():
        extra_parts.append(f"\n<context>\n{preloaded_context.strip()}\n</context>\n")
    return TASK_TEMPLATE.format(
        task_text=task_text.strip(),
        extra_context="".join(extra_parts),
        sentinel=COMPLETION_SENTINEL,
    )


def format_help_message() -> str:
    return FORMAT_HELP.format(sentinel=COMPLETION_SENTINEL) + "```\n"


def render_observation(*, returncode: int, output_text: str, remaining_steps: int) -> str:
    if remaining_steps <= 3:
        remaining_note = (
            f"[{remaining_steps} command(s) left. Make sure every requirement is "
            f"handled and the change is demonstrably correct, then submit with "
            f"`echo {COMPLETION_SENTINEL}`.]"
        )
    else:
        remaining_note = ""
    return OBSERVATION_TEMPLATE.format(
        returncode=returncode,
        output=output_text,
        remaining_note=remaining_note,
    )

# ---------- agent/repo_diff.py ----------
import os
import re
import subprocess

_SCRATCH_NAME_RE = re.compile(
    r"^(?:"
    r"(?:fix|clean|cleanup|mock|update|patch|apply|munge|tmp|temp|scratch|"
    r"run|do|gen|generate|rewrite|migrate|full|remove)_[\w.-]*\.py"
    r"|[\w.-]+\.(?:bak|orig|tmp|rej|swp|swo|new|fixed)"
    r"|[\w.-]+~"
    r")$",
    re.IGNORECASE,
)

_SHADOW_SUFFIXES = (".new", ".fixed", ".orig", ".bak", ".rej", ".tmp", ".swp", ".swo")


def collect_repo_patch(repo_dir: str) -> str:
    untracked = _untracked_files(repo_dir)
    _scrub_scratch(repo_dir, untracked)
    diff = _run_git(["diff", "--binary", "--", "."], repo_dir)
    listing = _run_git(["ls-files", "--others", "--exclude-standard", "-z"], repo_dir)
    for relative_path in [item for item in listing.split("\0") if item]:
        file_diff = _run_git_diff_no_index(relative_path, repo_dir)
        diff += file_diff
    return diff


def _untracked_files(repo_dir: str) -> list:
    listing = _run_git(["ls-files", "--others", "--exclude-standard", "-z"], repo_dir)
    return [item for item in listing.split("\0") if item]


def _scrub_scratch(repo_dir: str, untracked: list) -> None:
    """Delete agent-created scratch artifacts not referenced by a kept change."""
    try:
        if not untracked:
            return
        candidates = [
            p for p in untracked
            if "/" not in p.rstrip("/") and _SCRATCH_NAME_RE.match(os.path.basename(p))
        ]
        if not candidates:
            return
        kept_diff = _run_git(["diff", "--", "."], repo_dir) or ""
        keep_blob = kept_diff + "\n" + "\n".join(p for p in untracked if p not in candidates)
        for rel in candidates:
            base = os.path.basename(rel)
            abs_path = os.path.join(repo_dir, rel)
            shadow_of = None
            if base.endswith("~"):
                shadow_of = base[:-1]
            else:
                for suf in _SHADOW_SUFFIXES:
                    if base.lower().endswith(suf):
                        shadow_of = base[: -len(suf)]
                        break
            if shadow_of and os.path.exists(os.path.join(repo_dir, os.path.dirname(rel), shadow_of)):
                try:
                    if os.path.isfile(abs_path):
                        os.remove(abs_path)
                except OSError:
                    pass
                continue
            stem = os.path.splitext(base)[0]
            if stem and (stem in keep_blob or base in keep_blob):
                continue
            try:
                if os.path.isfile(abs_path):
                    os.remove(abs_path)
            except OSError:
                continue
    except Exception:
        return


def _run_git(args: list, repo_dir: str) -> str:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=repo_dir,
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return completed.stdout or ""


def _run_git_diff_no_index(relative_path: str, repo_dir: str) -> str:
    try:
        completed = subprocess.run(
            ["git", "diff", "--binary", "--no-index", "--", "/dev/null", relative_path],
            cwd=repo_dir,
            text=True,
            encoding="utf-8",
            errors="replace",
            capture_output=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    if completed.returncode in (0, 1):
        return completed.stdout or ""
    return ""

# ---------- agent/criteria.py ----------

import re

_INTEGRATION_RE = re.compile(
    r"\b(route|routing|router|provider|pipeline|middleware|handler|wire|integrat|"
    r"entrypoint|bootstrap|manifest|registry|extension|plugin|protocol|"
    r"config(?:uration)?|doc(?:umentation)?|tracking|changelog|readme)\b",
    re.I,
)
_COMPONENT_RE = re.compile(
    r"\b(?:reusable\s+)?component\b|`[A-Z][a-zA-Z0-9]+`",
    re.I,
)
_REFACTOR_RE = re.compile(
    r"\b(refactor|rename|restructur|convert|migrate|reorganiz)\b",
    re.I,
)
_NEW_SYMBOL_RE = re.compile(
    r"\b(create|add|introduce|new)\b",
    re.I,
)
_DATA_UPDATE_RE = re.compile(
    r"\b(json|csv|yaml|snapshot|equity|dashboard data|data file|"
    r"update the data|timestamp|prune|config file|\.json\b|\.csv\b)\b",
    re.I,
)
_UI_DETAIL_RE = re.compile(
    r"\b(animation|responsive|layout|sticky|AOS|glassmorphism|"
    r"hover|motion|typography|spacing|mobile)\b",
    re.I,
)


def _integration_hints(issue: str) -> list[str]:
    hints: list[str] = []
    if _DATA_UPDATE_RE.search(issue):
        hints.append(
            "If the task updates data/config/snapshot files, edit those files "
            "directly — do not refactor unrelated source code."
        )
    if _INTEGRATION_RE.search(issue):
        hints.append(
            "Wire changes into entrypoints, routes, providers, config, or docs — "
            "not orphan modules."
        )
    if _COMPONENT_RE.search(issue):
        hints.append(
            "For UI components, read the nearest sibling and mirror prop/callback "
            "naming and parent wiring — match this repo's patterns."
        )
    if _NEW_SYMBOL_RE.search(issue):
        hints.append(
            "Before new props, callbacks, keys, or handlers, grep for an analogous "
            "existing symbol and copy its naming convention."
        )
    if _REFACTOR_RE.search(issue):
        hints.append(
            "Refactor/rename in place; preserve working logic — do not delete source trees."
        )
    if _UI_DETAIL_RE.search(issue):
        hints.append(
            "UI polish tasks: implement every named visual/detail requirement "
            "(layout, animation, spacing) across all pages the task mentions."
        )
    return hints


def extract_criteria(issue: str) -> list[str]:
    lines = issue.splitlines()
    out: list[str] = []
    for line in lines:
        s = line.strip()
        if re.match(r"^[-*•]\s+\S", s):
            out.append(re.sub(r"^[-*•]\s+", "", s))
        elif re.match(r"^\d+[.)]\s+\S", s):
            out.append(re.sub(r"^\d+[.)]\s+", "", s))
    if not out:
        for m in re.finditer(
            r"(?:must|should|need to|ensure|remove|delete|rename|add)\s+[^.\n]{10,140}",
            issue,
            re.I,
        ):
            out.append(m.group(0).strip())
    for hint in _integration_hints(issue):
        if hint not in out:
            out.append(hint)
    return out[:15]


def format_checklist(criteria: list[str]) -> str:
    if not criteria:
        return ""
    rows = "\n".join(f"  {i + 1}. {c}" for i, c in enumerate(criteria))
    return f"\n## Acceptance checklist\nVerify every item before `echo` submit:\n{rows}\n"

# ---------- agent/guards.py ----------

import re
from typing import Optional

_FILE_IN_ISSUE_RE = re.compile(
    r"`?([\w./-]+\.(?:py|ts|tsx|js|jsx|go|rs|java|cs|rb|php|vue|html|css|json|yaml|yml|md|R|r|cpp|h|c|hpp|toml|xml|sql|sh|txt))`?",
    re.I,
)
_MUNGE_PATH_RE = re.compile(
    r"^(?:fix|clean|cleanup|replace|update|patch|apply|munge|modify|gen|generate|"
    r"rewrite|migrate|refactor)_[\w.-]+$",
    re.I,
)
_MUNGE_FILE_RE = re.compile(
    r"^(?:fix|update|replace|refactor|patch|apply|clean|generate|rewrite|migrate|"
    r"modify)_[\w.-]+\.(?:py|sh|js|ts|rb|pl)$",
    re.I,
)
_REFACTOR_ISSUE_RE = re.compile(
    r"\b(refactor|rename|restructur|convert|migrate|reorganiz)\b",
    re.I,
)


def _changed_paths(patch_text: str) -> list[str]:
    paths: list[str] = []
    for line in patch_text.splitlines():
        if line.startswith("+++ b/"):
            path = line[len("+++ b/") :].strip()
            if path and path != "/dev/null" and path not in paths:
                paths.append(path)
    return paths


def _line_stats(patch_text: str) -> tuple[int, int]:
    added = removed = 0
    for line in patch_text.splitlines():
        if line.startswith("+") and not line.startswith("+++"):
            added += 1
        elif line.startswith("-") and not line.startswith("---"):
            removed += 1
    return added, removed


def destructive_patch_reason(patch_text: str) -> Optional[str]:
    added, removed = _line_stats(patch_text)
    if removed >= 60 and added < max(5, removed // 4):
        return (
            f"the patch removes far more than it adds ({removed} deletions vs {added} additions); "
            "restore required logic instead of gutting the codebase"
        )
    return None


def munge_artifact_reason(patch_text: str) -> Optional[str]:
    for path in _changed_paths(patch_text):
        base = path.rsplit("/", 1)[-1]
        stem = base.rsplit(".", 1)[0] if "." in base else base
        if (
            _MUNGE_PATH_RE.match(stem)
            or _MUNGE_FILE_RE.match(base)
            or base.endswith((".new", ".bak", ".orig", ".tmp", ".rej"))
        ):
            return (
                f"the patch adds scratch or munge artifact `{path}`; "
                "edit source files directly and remove helper/backup files"
            )
    return None


def refactor_delete_reason(issue_text: str, patch_text: str) -> Optional[str]:
    if not _REFACTOR_ISSUE_RE.search(issue_text or ""):
        return None
    added, removed = _line_stats(patch_text)
    if removed >= 30 and added < max(8, removed // 3):
        return (
            f"refactor/rename task but patch mostly deletes code "
            f"({removed} deletions vs {added} additions); implement the change in place"
        )
    return None


def task_coverage_reason(issue_text: str, patch_text: str, repo_dir: Optional[str] = None) -> Optional[str]:
    mentioned = []
    for match in _FILE_IN_ISSUE_RE.finditer(issue_text):
        path = match.group(1).strip().lstrip("./")
        if path not in mentioned:
            mentioned.append(path)
    if not mentioned:
        return None
    touched = _changed_paths(patch_text)
    if not touched:
        return None

    # Filter mentioned files to only those that actually exist in the repo or are being touched/created.
    if repo_dir is not None:
        import os
        valid_mentioned = []
        for m in mentioned:
            # Check if the file exists on disk, or if it is a substring of any touched path,
            # or if any touched path ends with/contains it (e.g. m is "views.py" and t is "app/views.py").
            exists_on_disk = os.path.exists(os.path.join(repo_dir, m))
            is_touched = any(t == m or t.endswith("/" + m) or m.endswith("/" + t) for t in touched)
            if exists_on_disk or is_touched:
                valid_mentioned.append(m)
        mentioned = valid_mentioned

    if not mentioned:
        return None

    hit = sum(
        1
        for m in mentioned
        if any(t == m or t.endswith("/" + m) or m.endswith("/" + t) for t in touched)
    )
    if hit == 0:
        sample = ", ".join(mentioned[:6])
        return (
            f"the task names specific files ({sample}) but the patch does not touch any of them; "
            "find and edit the correct targets"
        )
    return None


def extended_repair_reason(issue_text: str, patch_text: str) -> Optional[str]:
    """Additional patch checks for the repair gate."""
    if not (patch_text or "").strip():
        return None
    for check in (
        destructive_patch_reason,
        munge_artifact_reason,
        lambda p: refactor_delete_reason(issue_text, p),
        lambda p: task_coverage_reason(issue_text, p),
    ):
        reason = check(patch_text)
        if reason:
            return reason
    return None


def patch_acceptable(patch_text: str) -> bool:
    if not patch_text.strip():
        return False
    if destructive_patch_reason(patch_text) or munge_artifact_reason(patch_text):
        return False
    return True

# ---------- agent/agent_loop.py ----------

import re
import time
from dataclasses import dataclass, field












_ACTION_BLOCK_RE = re.compile(r"```(?:bash|sh)?\s*\n(.*?)\n?```", re.DOTALL)
_MAX_FORMAT_RETRIES = 3


@dataclass
class AgentRunConfig:
    repo_dir: str
    model_name: str
    base_url: str
    auth_token: str
    max_steps: int = 50
    command_timeout: int = 15
    max_tokens: int = 8192
    max_observation_chars: int = 16000
    max_log_chars: int = 260000
    wall_clock_limit: float = 0.0


@dataclass
class AgentOutcome:
    success: bool
    patch: str
    logs: str
    steps: int
    cost: float | None
    message: str
    exit_status: str = "Submitted"
    transcript: list = field(default_factory=list)


def run_agent_loop(*, config: AgentRunConfig, task: str) -> AgentOutcome:
    model = ChatModel(
        model_name=config.model_name,
        base_url=config.base_url,
        auth_token=config.auth_token,
        max_completion_tokens=config.max_tokens,
    )
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": task if "<task>" in task else build_task_prompt(task_text=task)},
    ]
    started = time.monotonic()
    log_lines: list = []
    exit_status = "LimitsExceeded"
    message = f"step limit of {config.max_steps} reached"
    format_retries = 0

    for step in range(1, max(1, config.max_steps) + 1):
        if 0 < config.wall_clock_limit <= time.monotonic() - started:
            exit_status = "TimeExceeded"
            message = f"wall clock limit of {config.wall_clock_limit:.0f}s reached"
            break
        try:
            reply = model.query(messages)
        except ModelQueryError as exc:
            exit_status = "ModelError"
            message = str(exc)
            log_lines.append(f"[step {step}] model error: {exc}")
            break
        messages.append({"role": "assistant", "content": reply})
        log_lines.append(f"[step {step}] assistant:\n{reply}")

        actions = _ACTION_BLOCK_RE.findall(reply)
        commands = [action.strip() for action in actions if action.strip()]
        if len(commands) != 1:
            format_retries += 1
            if format_retries > _MAX_FORMAT_RETRIES:
                exit_status = "FormatError"
                message = "model kept replying without exactly one bash code block"
                break
            messages.append({"role": "user", "content": format_help_message()})
            log_lines.append(f"[step {step}] format retry {format_retries}")
            continue
        format_retries = 0
        command = commands[0]

        result = execute_command(command, cwd=config.repo_dir, timeout=config.command_timeout)
        output_text = result.get("output") or ""
        log_lines.append(f"[step {step}] $ {command}\n{truncate_text(output_text, 2000)}")
        if _is_submission(output_text, result.get("returncode")):
            exit_status = "Submitted"
            message = f"submitted after {step} step(s)"
            break
        observation = render_observation(
            returncode=int(result.get("returncode") or 0),
            output_text=truncate_text(output_text, config.max_observation_chars),
            remaining_steps=config.max_steps - step,
        )
        messages.append({"role": "user", "content": observation})

    patch = collect_repo_patch(config.repo_dir)
    logs = truncate_text("\n".join(log_lines), config.max_log_chars)
    return AgentOutcome(
        success=bool(patch.strip()),
        patch=patch,
        logs=logs,
        steps=model.calls,
        cost=None,
        message=message,
        exit_status=exit_status,
        transcript=messages,
    )


def _is_submission(output_text: str, returncode) -> bool:
    lines = output_text.lstrip().splitlines()
    return bool(lines) and lines[0].strip() == COMPLETION_SENTINEL and not returncode

# ---------- agent.py (entrypoint) ----------
#!/usr/bin/env python3
"""
Multi-file SWE coding agent for the tau subnet.

Contract (unchanged from the public single-file base agent):
    The validator imports this file and calls:

        solve(
            repo_path="/tmp/task_repo",
            issue="Fix the bug...",
            model="validator-managed-model",
            api_base="http://validator-proxy/v1",
            api_key="per-run-proxy-token"
        )

    It returns a dict with patch, logs, steps, cost, and success.

Layout:
    agent.py             validator-owned contract + thin solve() wiring
    agent/prompts.py     system/instance templates for complete, verified fixes
    agent/model.py       stdlib OpenAI-compatible chat client with retries
    agent/environment.py fresh-subshell bash executor
    agent/agent_loop.py  the query -> act -> observe step loop
    agent/repo_diff.py   harness-compatible patch collection
"""



import os
import json
import re
import subprocess
import time
import traceback
from typing import Any, Dict, Optional, Tuple













# -----------------------------
# Config
# -----------------------------

DEFAULT_MAX_STEPS = int(os.environ.get("AGENT_MAX_STEPS", "50"))
DEFAULT_COMMAND_TIMEOUT = int(os.environ.get("AGENT_COMMAND_TIMEOUT", "40"))

DEFAULT_MODEL = os.environ.get("AGENT_MODEL") or os.environ.get("NINJA_MODEL", "")
DEFAULT_API_BASE = (
    os.environ.get("AGENT_API_BASE")
    or os.environ.get("NINJA_INFERENCE_BASE_URL")
    or os.environ.get("OPENAI_BASE_URL", "")
)
DEFAULT_API_KEY = (
    os.environ.get("AGENT_API_KEY")
    or os.environ.get("NINJA_INFERENCE_API_KEY")
    or os.environ.get("OPENAI_API_KEY", "")
)
DEFAULT_MAX_TOKENS = int(os.environ.get("AGENT_MAX_TOKENS", "8192"))

MAX_OBSERVATION_CHARS = int(os.environ.get("AGENT_MAX_OBSERVATION_CHARS", "16000"))
MAX_TOTAL_LOG_CHARS = int(os.environ.get("AGENT_MAX_TOTAL_LOG_CHARS", "260000"))


def _wall_clock_limit_seconds() -> float:
    budget = os.environ.get("TAU_AGENT_TIMEOUT_SECONDS")
    if budget:
        try:
            return max(60.0, float(int(budget)) - 20.0)
        except ValueError:
            pass
    return 280.0


WALL_CLOCK_LIMIT_SECONDS = _wall_clock_limit_seconds()
WALL_CLOCK_RESERVE_SECONDS = 10.0


def _normalize_api_base(api_base: str) -> str:
    base = api_base.rstrip("/")
    if base.endswith("/chat/completions"):
        return base[: -len("/chat/completions")]
    if base.endswith("/v1"):
        return base
    return base + "/v1"


def _resolve_inference_config(
    model: Optional[str],
    api_base: Optional[str],
    api_key: Optional[str],
) -> Tuple[str, str, str]:
    model_name = (model or DEFAULT_MODEL).strip()
    base = (api_base or DEFAULT_API_BASE).strip()
    key = (api_key if api_key is not None else DEFAULT_API_KEY).strip()

    if not model_name:
        raise ValueError("model is required; validators must pass the centrally managed model id")
    if not base:
        raise ValueError("api_base is required; validators must pass the managed inference proxy URL")
    if not key:
        raise ValueError("api_key is required; validators must pass the per-run proxy token")

    return model_name, _normalize_api_base(base), key


def build_initial_user_prompt(issue: str, repo_summary: str, preloaded_context: str = "") -> str:
    base = build_task_prompt(task_text=issue, repo_summary=repo_summary, preloaded_context=preloaded_context)
    checklist = format_checklist(extract_criteria(issue))
    return base + checklist if checklist else base


VERIFY_REPAIR_MIN_BUDGET_SECONDS = 45.0
VERIFY_REPAIR_MAX_STEPS = 14


def _changed_py_files(patch_text: str) -> list:
    paths = []
    for line in patch_text.splitlines():
        if line.startswith("+++ b/"):
            path = line[len("+++ b/"):].strip()
            if path.endswith(".py") and path not in paths:
                paths.append(path)
    return paths


def _py_syntax_errors(repo_dir: str, patch_text: str) -> list:
    broken = []
    for rel in _changed_py_files(patch_text):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as handle:
                source = handle.read()
        except OSError:
            continue
        try:
            compile(source, rel, "exec")
        except SyntaxError as exc:
            broken.append(f"{rel}: line {exc.lineno}: {exc.msg}")
        except (ValueError, TypeError):
            broken.append(f"{rel}: could not be parsed")
    return broken


def _changed_source_files(patch_text: str, exts: tuple) -> list:
    paths = []
    for line in patch_text.splitlines():
        if line.startswith("+++ b/"):
            path = line[len("+++ b/"):].strip()
            if path.endswith(exts) and path not in paths:
                paths.append(path)
    return paths


def _run_check(cmd: list, cwd: str) -> Optional[str]:
    try:
        proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=20)
    except (OSError, ValueError, subprocess.SubprocessError):
        return None
    if proc.returncode == 0:
        return None
    msg = (proc.stderr or proc.stdout or "").strip()
    return (msg.splitlines()[0][:200] if msg else "failed syntax check")


_CS_REPEATED_BASE_RE = re.compile(
    r"\b(?:class|interface|struct|record)\s+[A-Za-z_]\w*(?:\s*<[^>]*>)?"
    r"\s*:\s*([A-Za-z_][\w.]*)(?:\s*:\s*\1\b)+"
)

_BRACE_BALANCE_EXTS = (".php", ".cs", ".kt", ".java", ".swift", ".scala")
_DELIM_OPEN = {")": "(", "]": "[", "}": "{"}


def _strip_code_noise(text: str) -> str:
    out = []
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            j = text.find("\n", i)
            i = n if j < 0 else j
            continue
        if c == "#":
            j = text.find("\n", i)
            i = n if j < 0 else j
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            j = text.find("*/", i + 2)
            if j < 0:
                return ""
            i = j + 2
            continue
        if c in "'\"`":
            quote = c
            i += 1
            while i < n:
                if text[i] == "\\":
                    i += 2
                    continue
                if text[i] == quote:
                    i += 1
                    break
                i += 1
            else:
                return ""
            continue
        out.append(c)
        i += 1
    return "".join(out)


def _delimiter_balance_error(text: str, rel: str):
    if "<<<" in text:
        return None
    code = _strip_code_noise(text)
    if not code:
        return None
    stack = []
    for idx, ch in enumerate(code):
        if ch in "([{":
            stack.append(ch)
        elif ch in ")]}":
            want = _DELIM_OPEN[ch]
            if not stack:
                return f"{rel}: unexpected closing '{ch}' (extra/dangling delimiter)"
            top = stack.pop()
            if top != want:
                return f"{rel}: mismatched '{ch}' (expected close for '{top}')"
    if stack:
        return f"{rel}: {len(stack)} unclosed '{stack[-1]}' delimiter(s) (missing close brace/paren)"
    return None


_DUP_DEF_EXTS = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".php", ".cs",
                 ".kt", ".java", ".go", ".swift", ".scala", ".rs")

_DUP_DEF_RE = re.compile(
    r"^[ \t]*"
    r"(?:export\s+)?(?:default\s+)?(?:public\s+|private\s+|protected\s+|internal\s+|static\s+|final\s+|abstract\s+|async\s+)*"
    r"(?:"
    r"(?:class|struct|enum|trait)\s+([A-Za-z_$][\w$]*)"
    r"|type\s+([A-Za-z_$][\w$]*)\s+(?:struct|interface)\b"
    r")",
    re.M,
)


def _duplicate_definition_error(text: str, rel: str):
    code = _strip_code_noise(text)
    if not code:
        return None
    seen = {}
    for mobj in _DUP_DEF_RE.finditer(code):
        name = mobj.group(1) or mobj.group(2)
        if not name:
            continue
        seen[name] = seen.get(name, 0) + 1
    dups = sorted(n for n, c in seen.items() if c > 1)
    if dups:
        return f"{rel}: duplicate top-level definition(s): {', '.join(dups[:4])} (defined more than once -> compile error)"
    return None


def _syntax_errors(repo_dir: str, patch_text: str) -> list:
    broken = []
    for rel in _changed_source_files(patch_text, (".py",)):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                source = fh.read()
        except OSError:
            continue
        try:
            compile(source, rel, "exec")
        except SyntaxError as exc:
            broken.append(f"{rel}: line {exc.lineno}: {exc.msg}")
        except (ValueError, TypeError):
            broken.append(f"{rel}: could not be parsed")
    for rel in _changed_source_files(patch_text, (".json",)):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                content = fh.read()
        except OSError:
            continue
        try:
            json.loads(content)
        except ValueError as exc:
            broken.append(f"{rel}: invalid JSON: {str(exc)[:120]}")
    for rel in _changed_source_files(patch_text, (".js", ".mjs", ".cjs")):
        err = _run_check(["node", "--check", rel], repo_dir)
        if err:
            broken.append(f"{rel}: {err}")
    for rel in _changed_source_files(patch_text, (".go",)):
        err = _run_check(["gofmt", "-e", rel], repo_dir)
        if err:
            broken.append(f"{rel}: {err}")
    for rel in _changed_source_files(patch_text, _BRACE_BALANCE_EXTS):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except OSError:
            continue
        err = _delimiter_balance_error(text, rel)
        if err:
            broken.append(err)
    for rel in _changed_source_files(patch_text, _DUP_DEF_EXTS):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except OSError:
            continue
        err = _duplicate_definition_error(text, rel)
        if err:
            broken.append(err)
    for rel in _changed_source_files(patch_text, (".php",)):
        err = _run_check(["php", "-l", rel], repo_dir)
        if err:
            broken.append(f"{rel}: {err}")
    for rel in _changed_source_files(patch_text, (".cs",)):
        full = os.path.join(repo_dir, rel)
        try:
            with open(full, "r", encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except OSError:
            continue
        if _CS_REPEATED_BASE_RE.search(_strip_code_noise(text)):
            broken.append(f"{rel}: malformed repeated base type (e.g. ': X : X')")
    return broken


def _all_changed_files(patch_text: str) -> list:
    out = []
    for line in patch_text.splitlines():
        if line.startswith("+++ b/"):
            p = line[len("+++ b/"):].strip()
            if p and p != "/dev/null" and p not in out:
                out.append(p)
    return out


def _is_test_path(path: str) -> bool:
    p = path.lower()
    base = p.rsplit("/", 1)[-1]
    if any(seg in ("test", "tests", "spec", "specs", "__tests__") for seg in p.split("/")[:-1]):
        return True
    if base.endswith(".py") and (base.startswith("test_") or base.endswith("_test.py") or base.startswith("test")):
        return True
    if ".test." in base or ".spec." in base or base.endswith("_spec.rb") or base.endswith("_test.go"):
        return True
    return False


def _source_files(patch_text: str) -> set:
    return {p for p in _all_changed_files(patch_text) if not _is_test_path(p)}


def _added_test_files(patch_text: str) -> list:
    return [p for p in _all_changed_files(patch_text) if _is_test_path(p)]


def _python_test_outcome(repo_dir: str, patch_text: str) -> str:
    tests = [p for p in _all_changed_files(patch_text)
             if _is_test_path(p) and p.endswith(".py")
             and os.path.isfile(os.path.join(repo_dir, p))]
    if not tests:
        return "none"
    rel = tests[0]
    for exe in ("python", "python3"):
        try:
            proc = subprocess.run(
                [exe, "-m", "pytest", rel, "-x", "-q", "-p", "no:cacheprovider"],
                cwd=repo_dir, capture_output=True, text=True, timeout=25,
            )
        except (OSError, ValueError, subprocess.SubprocessError):
            continue
        if proc.returncode == 0:
            return "pass"
        if proc.returncode == 1:
            return "fail"
        return "unknown"
    return "unknown"


def _repair_reason(repo_dir: str, patch_text: str, issue_text: str = "", check_tests: bool = True):
    if not (patch_text or "").strip():
        return ("empty", "the current change set is empty; no fix was produced yet")
    if check_tests:
        outcome = _python_test_outcome(repo_dir, patch_text)
        if outcome == "fail":
            return ("test_fail", "your own regression test currently FAILS, so the fix is wrong or incomplete; correct the fix until that test passes (never weaken the test).")
        if outcome == "none" and _source_files(patch_text) and not _added_test_files(patch_text):
            return ("no_test", "the fix changes source but includes no test proving it works; ADD one focused regression test that fails on the original bug and passes with your fix, and KEEP the existing source fix in place.")
    cov = task_coverage_reason(issue_text, patch_text, repo_dir=repo_dir)
    if cov:
        return ("coverage", cov)
    broken = _syntax_errors(repo_dir, patch_text)
    if broken:
        return ("syntax", "the edited files contain syntax errors that must be fixed:\n- " + "\n- ".join(broken[:8]))
    q = (
        destructive_patch_reason(patch_text)
        or munge_artifact_reason(patch_text)
        or refactor_delete_reason(issue_text, patch_text)
    )
    if q:
        return ("quality", q)
    return None


def _build_repair_task(issue_text: str, reason: str) -> str:
    return (
        "A previous attempt to solve the task below left the repository in an "
        "incomplete or broken state. " + reason + "\n\n"
        "Inspect the current state of the repository, then finish and correct "
        "the change so it fully and correctly solves the task. Re-read each "
        "edited region to confirm it is syntactically valid before submitting.\n\n"
        "Original task:\n" + issue_text
    )


def _build_polish_task(issue_text: str, reason: str) -> str:
    return (
        "A previous attempt successfully solved the task below, passed all tests, "
        "and has no syntax errors. Now, perform a polishing and refinement pass to "
        "ensure the solution is absolutely perfect, elegant, and production-ready.\n\n"
        "Specifically:\n"
        "1. Remove any unrelated edits, debug prints, or temporary comments.\n"
        "2. Ensure the code matches the existing style perfectly (indentation, quotes).\n"
        "3. Ensure the added regression test is robust, clean, and covers all edge cases.\n"
        "4. Make the changes as concise and precise as possible to minimize churn.\n\n"
        "Original task:\n" + issue_text
    )


def solve(
    repo_path: str,
    issue: str,
    model: Optional[str] = None,
    api_base: Optional[str] = None,
    api_key: Optional[str] = None,
    max_steps: int = DEFAULT_MAX_STEPS,
    command_timeout: int = DEFAULT_COMMAND_TIMEOUT,
    max_tokens: int = DEFAULT_MAX_TOKENS,
) -> Dict[str, Any]:
    started = time.monotonic()
    try:
        model_name, base_url, proxy_token = _resolve_inference_config(model, api_base, api_key)
        run_config = AgentRunConfig(
            repo_dir=repo_path,
            model_name=model_name,
            base_url=base_url,
            auth_token=proxy_token,
            max_steps=max_steps,
            command_timeout=command_timeout,
            max_tokens=max_tokens,
            max_observation_chars=MAX_OBSERVATION_CHARS,
            max_log_chars=MAX_TOTAL_LOG_CHARS,
            wall_clock_limit=WALL_CLOCK_LIMIT_SECONDS,
        )
        outcome = run_agent_loop(
            config=run_config,
            task=build_initial_user_prompt(issue, "", ""),
        )

        repair_note = ""
        try:
            remaining = WALL_CLOCK_LIMIT_SECONDS - (time.monotonic() - started)
            can_repair = remaining >= VERIFY_REPAIR_MIN_BUDGET_SECONDS
            reason = _repair_reason(repo_path, outcome.patch, issue_text=issue, check_tests=can_repair)
            if reason is None and can_repair:
                reason = ("polish", "The fix is correct and passes all tests, but we must polish and refine it to ensure it is of the highest quality, contains no unrelated churn, has clean and minimal edits, and is fully complete. Review your changes and make them perfect.")
            if reason is not None and can_repair:
                kind, message = reason
                orig_sources = _source_files(outcome.patch)
                repair_config = AgentRunConfig(
                    repo_dir=repo_path,
                    model_name=model_name,
                    base_url=base_url,
                    auth_token=proxy_token,
                    max_steps=min(max_steps, VERIFY_REPAIR_MAX_STEPS),
                    command_timeout=command_timeout,
                    max_tokens=max_tokens,
                    max_observation_chars=MAX_OBSERVATION_CHARS,
                    max_log_chars=MAX_TOTAL_LOG_CHARS,
                    wall_clock_limit=remaining - WALL_CLOCK_RESERVE_SECONDS,
                )
                if kind == "polish":
                    task_prompt = build_initial_user_prompt(_build_polish_task(issue, message), "", "")
                else:
                    task_prompt = build_initial_user_prompt(_build_repair_task(issue, message), "", "")
                repaired = run_agent_loop(
                    config=repair_config,
                    task=task_prompt,
                )
                rp = repaired.patch
                if rp.strip() and not _syntax_errors(repo_path, rp) and patch_acceptable(rp):
                    rtest = _python_test_outcome(repo_path, rp)
                    if kind == "empty":
                        adopt = rtest != "fail"
                    elif kind == "coverage":
                        adopt = rtest != "fail"
                    elif kind in ("syntax", "test_fail", "quality", "polish"):
                        adopt = rtest != "fail" and orig_sources.issubset(_source_files(rp))
                    else:
                        gained_test = bool(_added_test_files(rp)) and not _added_test_files(outcome.patch)
                        adopt = gained_test and rtest != "fail" and orig_sources.issubset(_source_files(rp))
                    if adopt:
                        outcome = repaired
                        repair_note = " (repair adopted: %s)" % kind
        except Exception:
            repair_note = " (repair pass skipped after error)"

        elapsed = time.monotonic() - started
        return {
            "patch": outcome.patch,
            "logs": outcome.logs,
            "steps": outcome.steps,
            "cost": outcome.cost,
            "success": outcome.success,
            "message": f"{outcome.exit_status}: {outcome.message} in {elapsed:.1f}s{repair_note}",
        }
    except Exception:
        fallback_patch = collect_repo_patch(repo_path)
        return {
            "patch": fallback_patch,
            "logs": traceback.format_exc()[-8000:],
            "steps": 0,
            "cost": None,
            "success": bool(fallback_patch.strip()),
            "message": "agent crashed; returning the on-disk repository diff",
        }
