#!/usr/bin/env python3
"""Flatten a package-shaped king (agent.py + agent/*.py) into one importable file.

The validator harness execs the king into a bare module named "agent" that has no
__path__, so `from agent.agent_loop import ...` and `from .model import ...` can
never resolve. A package king must be inlined before it can run at all.

Intra-package imports are located with the ast module, not a regex: several of the
king's imports span multiple lines inside parentheses, and a line-oriented filter
silently mangles them.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

# Leaves first, entrypoint last. agent_loop depends on environment/model/prompts/
# repo_diff; agent.py depends on everything.
MODULE_ORDER = [
    "environment", "model", "prompts", "repo_diff", "criteria", "guards", "agent_loop",
]


def strip_intra_package_imports(src: str) -> str:
    """Blank out `from .x import y` and `from agent.x import y` (any line span)."""
    tree = ast.parse(src)
    drop: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            is_relative = (node.level or 0) > 0
            is_agent_pkg = (node.module or "").split(".")[0] == "agent"
            is_future = node.module == "__future__"
            if is_relative or is_agent_pkg or is_future:
                drop.update(range(node.lineno, (node.end_lineno or node.lineno) + 1))
    lines = src.splitlines()
    return "\n".join("" if i + 1 in drop else ln for i, ln in enumerate(lines))


def flatten(root: Path) -> str:
    entry = root / "agent.py"
    pkg = root / "agent"
    if not entry.is_file():
        raise SystemExit(f"no agent.py under {root}")

    parts = [
        "#!/usr/bin/env python3",
        '"""Flattened king agent. Generated by scripts/flatten_king.py — do not edit."""',
        "from __future__ import annotations",
        "",
    ]
    for name in MODULE_ORDER:
        mod = pkg / f"{name}.py"
        if not mod.is_file():
            continue
        parts.append(f"# ---------- agent/{name}.py ----------")
        parts.append(strip_intra_package_imports(mod.read_text()))
        parts.append("")

    parts.append("# ---------- agent.py (entrypoint) ----------")
    parts.append(strip_intra_package_imports(entry.read_text()))
    return "\n".join(parts) + "\n"


def validate(src: str, path: str) -> None:
    """Fail loudly. A king that imports but has no solve() is worse than no king."""
    try:
        tree = ast.parse(src)
    except SyntaxError as e:
        raise SystemExit(f"flattened king does not parse: {e}")

    top = {n.name for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}
    if "solve" not in top:
        raise SystemExit("flattened king has no top-level solve()")

    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if (node.level or 0) > 0 or (node.module or "").split(".")[0] == "agent":
                raise SystemExit(f"unresolved intra-package import survived at line {node.lineno}")

    # Names used as `mod.attr` must actually be imported, or the king dies at runtime
    # exactly where KS41 died: a NameError that compiles fine.
    imported: set[str] = set()
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            imported.update((a.asname or a.name).split(".")[0] for a in n.names)
        elif isinstance(n, ast.ImportFrom):
            imported.update(a.asname or a.name for a in n.names)
    stdlib = {"os", "sys", "re", "json", "time", "subprocess", "traceback", "shutil",
              "tempfile", "ast", "signal", "urllib", "difflib", "textwrap", "random"}
    used = {n.value.id for n in ast.walk(tree)
            if isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name)}
    missing = sorted((used & stdlib) - imported)
    if missing:
        raise SystemExit(f"flattened king uses but never imports: {missing}")

    print(f"   validated: {len(src.splitlines())}L, top-level solve(), no dangling imports")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", help="dir holding agent.py and agent/")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    src = flatten(Path(args.root))
    validate(src, args.out)
    Path(args.out).write_text(src)
    print(f"   wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
